### ISSUE TITLE
Make RuntimeError public

### ISSUE THREAD

**Issue by rpecka** [apple/swift-openapi-runtime#98]
This error is thrown by the `.ok` getter but the only way to inspect it is via `.localizedDescription` or by casting it into `CustomStringConvertible` and checking `errorDescription`.

It would be nice if it was public so more details in the response can be extracted.

https://github.com/apple/swift-openapi-runtime/blob/76951d77a0609599d2dc233e7e40808a74767c6a/Sources/OpenAPIRuntime/Errors/RuntimeError.swift#L18

**Comment by czechboy0** [comment]
The error type being internal is intentional, the only way it's meant to be used is to ask it for a description, for example for logging. We want to retain the flexibility to evolve the type and change the description without breaking the public API.

What are you trying to do? If it's specifically about catching the error when an unexpected response code comes in then I'd recommend to not use the convenience throwing getter methods, and instead switch over the response type, which is a rich enum with associated values, and handle each case there.

**Comment by rpecka** [comment]
That makes sense -- I'll try the enum instead.
